# Generated by Django 4.1.13 on 2025-12-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='unit',
        ),
        migrations.AddField(
            model_name='user',
            name='unit_number',
            field=models.CharField(blank=True, help_text='House/Unit number for tenants', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('admin', 'Admin'), ('manager', 'Manager')], default='tenant', help_text='User role in the system', max_length=20),
        ),
    ]
