# Generated by Django 4.1.13 on 2025-12-17 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
